### ISSUE TITLE
Noms des packages incorrects

### ISSUE THREAD

**Issue by JustGeekFR** [Mateleo/spinel#2]
Bonjour,

J'ai remarqué un problème avec les packages Notepad++ et Epic Games Store. Les noms des dépôts sont incorrects. 

"notepad++" au lieu de "notepadplusplus"

"epicgamesstore" au lieu de "epicgameslauncher"

;-)

**Comment by Mateleo** [comment]
Hello !
Encore merci c'est corrigé ✨

PS : Très bon blog 😉

**Comment by JustGeekFR** [comment]
Merci c'est gentil ;-)
